# Generated by Django 5.2.1 on 2025-08-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('Price', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='ProductImages/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('brand_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.brand')),
                ('color_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.color')),
                ('type_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.type')),
                ('size_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.size')),
            ],
        ),
    ]
